public class myInterfaceImplementation implements  myInterface {
    
    public void myMethod(integer y){
        system.debug('printing from my method.');
    }
    public void mySecondMethod(){
        system.debug('priting from my Second method');
    }
    
    public void myThridMethod(){
        system.debug('priting from my third method');
    }
    
    public void myFourthMethod(){
        system.debug('hi there');
    }
    

}